MM-1835, removed asserts that were deemed too strict.
Nictiz/Nictiz-STU3-testscripts-src pull request #12
Opened 2021-03-05 13:04 UTC by VincentGoris

2021-03-05 13:44 UTC, ArdonToonstra requested changes

2021-03-05 13:44 UTC, ArdonToonstra commented on dev/FHIR3-0-2-MM202001-Cert/PDFA-3-0/PHR-Client/medmij-pdfa-phr-3-1-send-1-document.xml
> -            <direction value="response"/>
Misschien moeten we in plaats van verwijderen, de direction zetten op request?

2021-03-08 11:05 UTC, VincentGoris commented
Heb de wijziging doorgevoerd, was nodig om een nieuwe common assert in te bouwen. Vandaar ook Jorn toegevoegd als reviewer. getest in touchstone, links staat in het issue. Nieuwe test slaagt.

2021-03-08 17:08 UTC, ArdonToonstra submitted a review, later dismissed
Zoals ook met Jorn besproken is de toevoeging vna de common-assert hier ok!
In het vervolg zou het fijn zijn als je de source bestanden in een andere commit zit dan de gegenereerde bestanden. Dat houd het wat overzichtelijker.
Heb een foutje gevonden. Zie comment.

2021-03-08 17:08 UTC, ArdonToonstra commented on src/common-asserts/assert-requestCount.xml
> +            <description value="Confirm that the returned searchset Bundle contains {$count} {$resource} resource(s). {$additionalDescription}"/>
Dit is nog niet aangepast. De description gaat hier nog over de returned searchset Bundle.

2021-03-12 11:01 UTC, jduwel requested changes
Top. Nu nog de output opnieuw draaien en committen

2021-03-12 11:03 UTC, jduwel commented
In z'n algemeenheid: in de diverse commits staan nu TestScripts waarin alleen de datum is aangepast en niks inhoudelijks. Voor de middellange termijn gaan we hier een oplossing voor zoeken dat de implementers hier geen rekening mee hoeven te houden, maar voor nu is het wel netter om alleen de output waar daadwerkelijk iets inhoudelijks veranderd is te committen.

2021-03-22 10:22 UTC, jduwel approved these changes

2021-03-22 15:25 UTC, merged