MM-3136. Regenerated Touchstone stuff for AllerIntolerance-3.0.
Nictiz/Nictiz-STU3-testscripts-src pull request #153
Opened 2022-07-13 11:59 UTC by NictizEduard

2022-07-19 09:56 UTC, pieter-edelman-nictiz requested changes

2022-07-19 09:56 UTC, pieter-edelman-nictiz commented on src/AllergyIntolerance-3-0/Cert/_reference/AllergyIntolerance20/nl-core-practitionerrole-cio-1111111210100.xml
> -   <identifier>
Deze handmatig toegevoegde identifiers vallen er nu weer uit. Is dat de bedoeling?

2022-07-19 13:18 UTC, pieter-edelman-nictiz commented on src/AllergyIntolerance-3-0/Cert/_reference/AllergyIntolerance20/nl-core-practitionerrole-cio-1111111210100.xml
> -   <identifier>
Ai, dat had ik gemist. Never mind.

2022-07-19 13:19 UTC, pieter-edelman-nictiz requested changes
Deze bundels horen dan weer niet bij MM-3136, toch?

2022-07-19 13:25 UTC, NictizEduard commented
> Deze bundels horen dan weer niet bij MM-3136, toch?

Klopt, ik heb in een verkeerde branche gepushed. Daarom is de commit er na "Revert..."

2022-07-21 08:19 UTC, pieter-edelman-nictiz approved these changes

2022-07-25 07:42 UTC, pieter-edelman-nictiz commented
Handmatig gemerged

2022-07-25 07:42 UTC, closed without merging