MM-2384, changed one of the common asserts to correctly assert refere…
Nictiz/Nictiz-STU3-testscripts-src pull request #53
Opened 2021-09-03 13:47 UTC by VincentGoris

…nces and used build-all to recreate all testscripts

Common assert aangepast, build-all gedraaid en getest in touchstone. Testen gaat goed. Kan eventueel nog een test doen waarbij een reference.reference wordt verwerkt in het kwalificatiemateriaal om te bevestigen dat het buiten Fhirpath ook goed gaat, is dat nuttig?

2021-09-03 14:34 UTC, ArdonToonstra commented
Goed bezig!
>Kan eventueel nog een test doen waarbij een reference.reference wordt verwerkt in het kwalificatiemateriaal om te bevestigen dat het buiten Fhirpath ook goed gaat, is dat nuttig?

Dit zou wel top zijn. Dan weten we iig ook zeker dat we iets aan het oplossen zijn. Zou je dan ook het Touchstone linkje willen delen?

Zou je in het vervolg de aanpassing in de source folder apart willen doen van de gegenereerde output? Dat is makkelijker controleren. Volgens mij zijn dat ook de huidige werkafspraken.

2021-09-08 13:40 UTC, VincentGoris commented
Test inclusief het .actor element zoals de leverancier het had getest. Levert een warning op vanwege actor.role, maar dat staat hier verder los van. Geen error, test doet het zoals het moet. https://touchstone.aegis.net/touchstone/scriptexecution?exec=202109080937245459182280&qn=/FHIRSandbox/Nictiz/dev/FHIR3-0-2-MM202001-Test/BgZ-3-0/XIS-Server/medmij-bgz-xis-1-1-serve-bgz-xml#WAITING_OPER

2021-09-08 15:15 UTC, ArdonToonstra approved these changes
Ziet er goed uit!

2021-09-15 07:55 UTC, pieter-edelman-nictiz requested changes
A lot of files have been deleted in this commit. This doesn't seem to be in scope for this issue. Is this actually correct? @ArdonToonstra  @VincentGoris

2021-09-15 07:55 UTC, pieter-edelman-nictiz commented on src/Medication-9-0-7/null13874372238583739743.txt
> +fixtures=;
Why is this file included?

2021-09-15 07:55 UTC, pieter-edelman-nictiz commented on src/Medication-9-0-7/null3399783505073903609.txt
> +fixtures=;
Why is this file included?

2021-09-15 08:29 UTC, ArdonToonstra commented
You are right. I missed all the deletes for some reason. No sure what's going on here. @VincentGoris can you explain?

2021-09-15 14:21 UTC, pieter-edelman-nictiz approved these changes

2021-09-20 08:52 UTC, merged